CREATE TABLE IF NOT EXISTS Host (
	Id INTEGER PRIMARY KEY,
	Name TEXT NOT NULL,
	Host TEXT NOT NULL,
	Port INTEGER NOT NULL,
	Username TEXT NOT NULL,
	Password TEXT NOT NULL,
	Created TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Job (
	Id INTEGER PRIMARY KEY,
	Name TEXT NOT NULL,
	HostId TEXT NOT NULL,
	Created TEXT NOT NULL,
	FOREIGN KEY(HostId) REFERENCES Host(Id)
);